services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $minkParameters: '@behat.mink.parameters'

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
